# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd6340d5296d3065522d7819ac641357e05f5aec8e1b27d79ad32f7900113a50311c62285d12bedf255123b078705e551eae8bcf2265bb95a2889b3248f258a

test:
  secret_key_base: 0fd60585c62221b1ef25ea3c8e723c696af99bed07c3a00e8efdafc497c6f67a5f45904aa17015b1290c3aadc8c9c1d0f365d25102fcd698d9a179d7605914fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
